server:
  port: 8080

logging:
  level:
    root: TRACE

spring:
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set: http://localhost:9000/oauth2/jwks